### ISSUE TITLE
Validator is not properly displaying existence of stats on amiibo with no skills or type (but is nonetheless returning the correct value for Vanilla)

### ISSUE THREAD

**Issue by burbidgephilip** [fudgepop01/amiibo-validator#1]
This is definitely a niche case and is probably not going to crop up often for average users, but the validator seems to be incorrectly flagging green for "Stats" on spirited amiibo with stats but without type or skills. This can result in a spirited amiibo being correctly reported as not being vanilla despite simultaneously being incorrectly reported as fulfilling all the criteria to be vanilla. Note the difference between these two, one of which is genuinely vanilla and the other of which has stats but Neutral type and no skills: 
![image](https://user-images.githubusercontent.com/35292784/84582380-19f3c480-ada0-11ea-9746-22665ed2182f.png)

I am going to pull the code and see whether I can figure our why this is occurring--but (as evidenced by my GitHub) I am not an experienced coder and you'll probably sort it before I am able to.

EDITED: Typos fixed, and correct screenshot added in place of incorrect and useless one.

**Comment by burbidgephilip** [comment]
I've done a bit of further testing to see where the issue may lie. All amiibo in the attached screenshot display 100% correctly except the spirits Isabelle previously noted and the Ryu and Mega Man at the bottom of this screenshot. (Please forgive me for not renaming those before taking the screenshot; they're old spirits bins of mine that I just pulled out of my archives to test this.) Like the Isabelle, the Mega Man and Ryu have no skills; unlike the Isabelle, though, those two are both typed (specifically, both are Attack type). This suggests that there may something about the scanned amiibo having no skills which causes the program to display green for "Stats" whether stats are present or not; though, again, this does not seem to be affecting the program's ability to correctly identify an amiibo as "not vanilla."
![image](https://user-images.githubusercontent.com/35292784/84583664-b2457580-adaf-11ea-8d68-40fafc8eaf60.png)

**Comment by fudgepop01** [comment]
Hey, thanks a bunch for looking into it so much! I actually just looked into it. The file itself isn't too complex, so it was fairly easy to figure out what went wrong - _especially_ with the information you gave me (which was very helpful tysm)

![image](https://user-images.githubusercontent.com/3662774/84584479-fa29c400-add2-11ea-887d-926488174645.png)

here I have `spiritMod` checked for `statModOut` _instead of_ `statMod`. It's a small mistake that I'm glad folks like you picked up on and reported so quickly.

I should have a fix out relatively soon!~

**Comment by fudgepop01** [comment]
aaand fixed! Check the `Releases` section of this repository for the updated version. Thanks again!
